#!/bin/bash

set -eEu
set -o pipefail

. sdlc/bootstrap
. sdlc/vars

python3 -m pre_commit run --all-files --hook-stage manual

docker-compose up -d
sleep 5

echo
echo "[*] Test completed successfully!"
echo
